#!/bin/sh
mktun snow0 snow
ip addr add dev snow0 10.144.0.1/12
ip link set snow0 mtu 1419 up

iptables -I INPUT -s 10.144.0.0/12 ! -i snow0 -j DROP
iptables -I INPUT -s 10.144.0.1 -i lo -j ACCEPT

su snow -c "authbind /usr/sbin/snowd"
